### ISSUE TITLE
Investigate / Spike - if an abrupt end happens to a gateway connection via the socks-5 / nym-client (system shutdown / restart) - when I reboot the my system and I try to start the process again, I'm hit with the following:

### ISSUE THREAD

**Issue by tommyv1987** [nymtech/nym#1129]
```
2022-02-23T14:51:49.411Z INFO  nym_socks5_client::client        > Starting received messages buffer controller...
thread 'main' panicked at 'could not authenticate and start up the gateway connection: GatewayError("There is already an open connection to this client")', clients/socks5/src/client/mod.rs:194:14
stack backtrace:
   0: rust_begin_unwind
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:498:5
   1: core::panicking::panic_fmt
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/panicking.rs:107:14
   2: core::result::unwrap_failed
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/result.rs:1613:5
   3: core::result::Result<T,E>::expect
             at /rustc/db9d1b2
```

The remedy to the solution was not from the client side, but I had to restart the gateway that the client was connected to.

After the service was restarted, and the socks-5-client was `run` the client was able to successfully able to connect again

**Comment by tommyv1987** [comment]
```
2022-02-23T14:51:49.411Z INFO  nym_socks5_client::client        > Starting received messages buffer controller...
thread 'main' panicked at 'could not authenticate and start up the gateway connection: GatewayError("There is already an open connection to this client")', clients/socks5/src/client/mod.rs:194:14
stack backtrace:
   0: rust_begin_unwind
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:498:5
   1: core::panicking::panic_fmt
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/panicking.rs:107:14
   2: core::result::unwrap_failed
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/result.rs:1613:5
   3: core::result::Result<T,E>::expect
             at /rustc/db9d1b2
```

The remedy to the solution was not from the client side, but I had to restart the gateway that the client was connected to.

After the service was restarted, and the socks-5-client was `run` the client was able to successfully able to connect again

**Comment by tommyv1987** [comment]
A lot of improvements on SIGINT and handling has been introduced since this ticket has been raised, I haven't been able to reproduce this lately, therefore closing this.
