### ISSUE TITLE
[Issue] network-requester crashed

### ISSUE THREAD

**Issue by sven-hash** [nymtech/nym#1448]
**Describe the issue**
When trying to download a 10GB file from speed.hetzner.de in order to test the mixnet, the nym-network crash

**Expected behaviour**
Downloaded completely the file

**Stack Traces**
```
2022-07-07T17:56:52.582Z INFO  nym_network_requester::core > Starting proxy for speed.hetzner.de:443 (currently there are 1 proxies being handled)
thread 'main' panicked at 'we failed to read from the websocket!: Io(Os { code: 104, kind: ConnectionReset, message: "Connection reset by peer" })', service-providers/network-requester/src/core.rs:thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Io(Os { code: 32, kind: BrokenPipe, message: "Broken pipe" })75:18
', service-providers/network-requester/src/core.rsnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Steps to Reproduce**
1. Start the `network-request --open-proxy`
2. Start the nym-socks5 and connect to the nym-client that use the network-requester
3. Download the file `curl --socks5-hostname localhost:1080  https://speed.hetzner.de/10GB.bin`

*An example:*
- Given I was setting up a mix-node following the instructions in the docs
- And I successfully bonded my node via the the wallet
- When I went to start my mixnode
- Then I was presented with an error

**Which area of Nym were you using?**
 - Application: network-requester 1.0.1

**Comment by sven-hash** [comment]
Here's the full stack

```
All systems go. Press CTRL-C to stop the server.
 2022-07-07T18:04:19.398Z INFO  nym_network_requester::core > Starting proxy for speed.hetzner.de:443 (currently there are 1 proxies being handled)
thread 'main' panicked at 'we failed to read from the websocket!: Io(Os { code: 104, kind: ConnectionReset, message: "Connection reset by peer" })', service-providers/network-requester/src/core.rs:75:18
stack backtrace:
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Io(Os { code: 32, kind: BrokenPipe, message: "Broken pipe" })', service-providers/network-requester/src/core.rs:66:50
   0: rust_begin_unwind
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/panicking.rs:143:14
   2: core::result::unwrap_failed
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/result.rs:1749:5
   3: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   4: std::thread::local::LocalKey<T>::with
   5: tokio::park::thread::CachedParkThread::block_on
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Aborted (core dumped)
```
