### ISSUE TITLE
[Issue] this endpoint must be available over WSS

### ISSUE THREAD

**Issue by sven-hash** [nymtech/nym#1778]
**Describe the issue**
It's not possible to use wasm client over HTTPS since the websocket connection to the gateway listener is not possible considered as secure. It must use wss:// protocol

**Expected behaviour**
Connection to the gateway and receive client id

**Stack Traces**

```
0a42b3b883d0eee102fc.js:1 Mixed Content: The page at 'https://pastenym.ch/268.bundle.js' was loaded over HTTPS, but attempted to connect to the insecure WebSocket endpoint 'ws://213.219.38.119:9000/'. This request has been blocked; this endpoint must be available over WSS.
(anonymous) @ 0a42b3b883d0eee102fc.js:1
U @ 0a42b3b883d0eee102fc.js:1
F._.wbg.__wbg_new_d29e507f6606de91 @ 0a42b3b883d0eee102fc.js:1
$func2313 @ 74a21f98aaa34362aeca.wasm:0xc5d7d
$func296 @ 74a21f98aaa34362aeca.wasm:0x57e09
$func1295 @ 74a21f98aaa34362aeca.wasm:0xa6d4a
$func257 @ 74a21f98aaa34362aeca.wasm:0x504ab
$func244 @ 74a21f98aaa34362aeca.wasm:0x4d60c
$func249 @ 74a21f98aaa34362aeca.wasm:0x4e940
$func1167 @ 74a21f98aaa34362aeca.wasm:0xa0feb
$func655 @ 74a21f98aaa34362aeca.wasm:0x81e0a
$func1444 @ 74a21f98aaa34362aeca.wasm:0xacdca
$func964 @ 74a21f98aaa34362aeca.wasm:0x969cd
$_dyn_core__ops__function__FnMut__A____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__ha45641151c24b06a @ 74a21f98aaa34362aeca.wasm:0xddbc1
R @ 0a42b3b883d0eee102fc.js:1
i @ 0a42b3b883d0eee102fc.js:1
0a42b3b883d0eee102fc.js:1 panicked at 'could not authenticate and start up the gateway connection: NetworkErrorWasm(JsValue(SecurityError: Failed to construct 'WebSocket': An insecure WebSocket connection may not be initiated from a page loaded over HTTPS.
Error: Failed to construct 'WebSocket': An insecure WebSocket connection may not be initiated from a page loaded over HTTPS.
    at https://pastenym.ch/0a42b3b883d0eee102fc.js:1:13422
    at U (https://pastenym.ch/0a42b3b883d0eee102fc.js:1:3208)
    at F._.wbg.__wbg_new_d29e507f6606de91 (https://pastenym.ch/0a42b3b883d0eee102fc.js:1:13396)
    at https://pastenym.ch/74a21f98aaa34362aeca.wasm:wasm-function[2313]:0xc5d7d
    at https://pastenym.ch/74a21f98aaa34362aeca.wasm:wasm-function[296]:0x57e09
    at https://pastenym.ch/74a21f98aaa34362aeca.wasm:wasm-function[1295]:0xa6d4a
    at https://pastenym.ch/74a21f98aaa34362aeca.wasm:wasm-function[257]:0x504ab
    at https://pastenym.ch/74a21f98aaa34362aeca.wasm:wasm-function[244]:0x4d60c
    at https://pastenym.ch/74a21f98aaa34362aeca.wasm:wasm-function[249]:0x4e940
    at https://pastenym.ch/74a21f98aaa34362aeca.wasm:wasm-function[1167]:0xa0feb))', src/client/mod.rs:215:14
```

**Steps to Reproduce**
Steps to reproduce the behaviour, if you're familiar with BDD syntax, please write it in this style:
- Given I was doing X
- And I installed Y
- When I actioned Y
- Then I expect Z

*An example:*
- Given I was setting up a mix-node following the instructions in the docs
- And I successfully bonded my node via the the wallet
- When I went to start my mixnode
- Then I was presented with an error

**Screenshots**
![](https://i.imgur.com/O7L1rKj.png)

**Which area of Nym were you using?**
 - Application: [wasm-Client]
 - Browser: [Firefox, Brave]
 - Version: ["@nymproject/sdk": "^1.1.4"]

**Additional context**

Provide a way to set an endpoint that use `wss://`

**Comment by tommyv1987** [comment]
@sven-hash we're going to be tackling this one this week. We aim to having something sorted asap.
