### ISSUE TITLE
Telnet panics native client

### ISSUE THREAD

**Issue by futurechimp** [nymtech/nym#248]
While writing the docs, I was hoping to ask the user to test that the websocket started up properly on the native client, by doing: 

```
telnet 127.0.0.1 1977
Trying 127.0.0.1...
Connected to 127.0.0.1.
Escape character is '^]'.
^]
telnet> quit
Connection closed.
```

Telnet connects fine, but ending the session normally as above results in: 

```
 2020-06-01T12:15:56.623 WARN  nym_client::websocket::handler          > error while performing the websocket handshake - Io(Custom { kind: Other, error: "Handshake not finished" })
thread 'tokio-runtime-worker' panicked at 'trying to disconnect non-existent sender!', clients/desktop/src/client/received_buffer.rs:66:13
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1063
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1426
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:204
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:224
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:470
  11: std::panicking::begin_panic
  12: <std::future::GenFuture<T> as core::future::future::Future>::poll
  13: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Aborted (core dumped)
```

**Comment by tommyv1987** [comment]
Can no longer reproduce this, closing.
