### ISSUE TITLE
[Issue] WASM got error when RawMessage is received

### ISSUE THREAD

**Issue by sven-hash** [nymtech/nym#3345]
**Describe the issue**
Receive an error in browser when a service provider reply by using a raw message

`panicked at 'range end index 1920166263 out of range for slice of length 112', src/encoded_payload_helper.rs:93:45`

**Expected behaviour**
No error

**Stack Traces**

```
f4d29e-c9b2-408f-b965-c788ef19f7b4:1536 panicked at 'range end index 1920166263 out of range for slice of length 112', src/encoded_payload_helper.rs:93:45

Stack:

Error
    at imports.wbg.__wbg_new_abda76e883ba8a5f (blob:http://localhost:8081/5df4d29e-c9b2-408f-b965-c788ef19f7b4:1524:23)
    at wasm://wasm/006066ea:wasm-function[813]:0x9f03d
    at wasm://wasm/006066ea:wasm-function[5548]:0x1064a4
    at wasm://wasm/006066ea:wasm-function[1192]:0xb55aa
    at wasm://wasm/006066ea:wasm-function[1603]:0xc75a3
    at wasm://wasm/006066ea:wasm-function[4238]:0xfdeb6
    at wasm://wasm/006066ea:wasm-function[2716]:0xe710a
    at wasm://wasm/006066ea:wasm-function[3642]:0xf697c
    at wasm://wasm/006066ea:wasm-function[2019]:0xd5765
    at wasm://wasm/006066ea:wasm-function[5231]:0x105433


i
```

**Steps to Reproduce**
 
1. Set a listener
```
this.nym.events.subscribeToRawMessageReceivedEvent((e) => {
            console.log(e.args.payload)
        })
```
2. Wait for a message

**Which area of Nym were you using?**
 - Version: [@nymproject/sdk 1.1.7]

**Comment by mmsinclair** [comment]
@sebastinez hopefully we can tidy up the handling of errors a bit more

**Comment by sven-hash** [comment]
Still occur in 1.2.1

**Comment by mmsinclair** [comment]
Will look at #4102 as soon as I can
