### ISSUE TITLE
Gateway unresponsive

### ISSUE THREAD

**Issue by futurechimp** [nymtech/nym#347]
My Nym socks5 client became unresponsive - attempting to restart the socks5 client results in the following stack trace:

```
$ target/release/nym-socks5-client run --id nym-testnet-socks5-requester


      _ __  _   _ _ __ ___
     | '_ \| | | | '_ \ _ \
     | | | | |_| | | | | | |
     |_| |_|\__, |_| |_| |_|
            |___/

             (socks5 proxy - version 0.8.0)

    


If unsure which gateway to choose - 'D6YaMzLSY7mANtSQRKXsmMZpqgqiVkeiagKM4V4oFPFr' is a safe choice for the testnet


 2020-09-25T19:19:12.819 INFO  nym_socks5_client::client > Starting nym client
 2020-09-25T19:19:12.842 INFO  nym_socks5_client::client > Obtaining initial network topology from https://directory.nymtech.net
 2020-09-25T19:19:13.226 INFO  nym_socks5_client::client > Starting topology refresher...
 2020-09-25T19:19:13.226 INFO  nym_socks5_client::client > Starting received messages buffer controller...
thread 'main' panicked at 'could not authenticate and start up the gateway connection: GatewayError("unexpected failure")', clients/socks5/src/client/mod.rs:199:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Aborted (core dumped)
```

For whatever reason, there's no way to restart the socks5 client, that error keeps happening. 

We will need to investigate this on Monday, I suspect that there are a bunch of small fixes we'll need to bundle into a 0.8.1 release.

**Comment by futurechimp** [comment]
Still getting this today, after a full network switch (connect to proxy while on wifi, switch wifi networks, attempt to resume). 

```$ target/release/nym-socks5-client run --id nym-testnet-socks5-requester


      _ __  _   _ _ __ ___
     | '_ \| | | | '_ \ _ \
     | | | | |_| | | | | | |
     |_| |_|\__, |_| |_| |_|
            |___/

             (socks5 proxy - version 0.8.1)

    
 2020-10-02T17:25:17.156 INFO  nym_socks5_client::client > Starting nym client
 2020-10-02T17:25:17.186 INFO  nym_socks5_client::client > Obtaining initial network topology from https://directory.nymtech.net
 2020-10-02T17:25:18.272 INFO  nym_socks5_client::client > Starting topology refresher...
 2020-10-02T17:25:18.272 INFO  nym_socks5_client::client > Starting received messages buffer controller...
thread 'main' panicked at 'could not authenticate and start up the gateway connection: GatewayError("unexpected failure")', clients/socks5/src/client/mod.rs:194:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Aborted (core dumped)```

Could be related to #362 according to @jstuczyn

**Comment by tommyv1987** [comment]
This is outdated now, and we're about to release v1.0.2 - I have not encountered this issue whilst testing all the new binaries. Therefore, im going to close this issue, but if it arises again  we can use this as a aplaceholder.

**Comment by octol** [comment]
I'm getting hit by this when testing 1.1.1 on mainnet, so unfortunately I think this is still an open issue.
Also see https://github.com/nymtech/nym/issues/1129 which I think describes the same issue

**Comment by tommyv1987** [comment]
We have encountered this in a while, nor have we since this error message, therefore, im closing this guy, as a lot of deployments have happened since.
