### ISSUE TITLE
[Issue] Wallet: Pressing Ctrl+R reloads the app with broken state

### ISSUE THREAD

**Issue by nadimkobeissi** [nymtech/nym#3489]
## Steps to reproduce

1. Open Nym Wallet
2. Sign in, etc.
3. Press Ctrl+R (on macOS, try Cmd+R)
4. App "refreshes" like a browser window, and subsequent attempts to log in don't work due to broken state.

## Expected behavior

Pressing Ctrl+R/Cmd+R shouldn't do anything.

**Comment by nadimkobeissi** [comment]
Pressing F5 also triggers the issue.

**Comment by tommyv1987** [comment]
This is not applicable on production versions of the wallet, so this is not a major issue.

However, when launching in dev mode or compiling the wallet locally, when hot refreshing it tries to use the same port address, one to look at in the future:
```
Error: listen EADDRINUSE: address already in use :::9000
    at Server.setupListenHandle [as _listen2] (node:net:1319:16)
    at listenInCluster (node:net:1367:12)
    at Server.listen (node:net:1454:7)
    at READ_WRITE (/Users/Documents/NYM_Production/nym/node_modules/webpack-dev-server/lib/Server.js:3328:23)
    at new Promise (<anonymous>)
    at Server.start (/Users/Documents/NYM_Production/nym/node_modules/webpack-dev-server/lib/Server.js:3326:7)
    at async Command.<anonymous> (/Users/Documents/NYM_Production/nym/node_modules/@webpack-cli/serve/lib/index.js:257:25)
    at async Promise.all (index 1)
    at async Command.<anonymous> (/Users/Documents/NYM_Production/nym/node_modules/webpack-cli/lib/webpack-cli.js:1372:13) {
  code: 'EADDRINUSE',
  errno: -48,
  syscall: 'listen',
  address: '::',
  port: 9000
}
```

**Comment by nadimkobeissi** [comment]
@tommyv1987 Beg to differ, this is very applicable on production versions of the wallet. Could reproduce on Nym Wallet v1.2.3 downloaded from https://nymtech.net on my Windows machine.
