### ISSUE TITLE
NC fail to reconnect after suspend mode on ubuntu

### ISSUE THREAD

**Issue by rachyandco** [nymtech/nym#3762]
**Describe the issue**
Running Nym connect 1.1.16 on Ubuntu 22.04.3 LTS. The network is connected through the wifi. The computer is then put on suspend mode (closing the lid of the laptop). When waking up, Nym connect fails to reconnect.

**Expected behaviour**
Nym-connect should reconnect when network is available.

**Stack Traces**
```
[2023-08-12][08:48:45] INFO  nym_socks5_client_core::socks::client  > Starting proxy for 91.108.56.171:80 (id: 13284288644269231055)
[2023-08-12][08:48:46] ERROR nym_gateway_client::client  > failed to send message without response - There was a network error - IO error: Connection reset by peer (os error 104)...
[2023-08-12][08:48:46] ERROR nym_gateway_client::client  > ... and the delegated stream has also errored out - There was a network error - IO error: Broken pipe (os error 32)
[2023-08-12][08:48:46] INFO  nym_gateway_client::client  > Attempting gateway reconnection...
[2023-08-12][08:48:46] INFO  nym_gateway_client::client  > attempt 1...
[2023-08-12][08:48:46] INFO  nym_socks5_client_core  > Task error: UnexpectedHalt
[2023-08-12][08:48:46] INFO  nym_socks5_client_core  > Sending shutdown
[2023-08-12][08:48:46] INFO  nym_socks5_client_core  > Waiting for tasks to finish... (Press ctrl-c to force)
[2023-08-12][08:48:46] INFO  nym_client_core::client::replies::reply_storage  > PersistentReplyStorage is flushing all reply-related data to underlying storage
[2023-08-12][08:48:46] WARN  nym_client_core::client::replies::reply_storage  > you MUST NOT forcefully shutdown now or you risk data corruption!
[2023-08-12][08:48:46] INFO  nym_client_core::client::replies::reply_storage::backend::fs_backend::manager  > Database migration finished!
[2023-08-12][08:48:46] INFO  nym_client_core::client::replies::reply_storage  > Data flush is complete
[2023-08-12][08:48:51] INFO  nym_task::manager  > Timeout reached, forcing shutdown
[2023-08-12][08:48:51] INFO  nym_socks5_client_core  > Stopping nym-socks5-client
[2023-08-12][08:48:51] ERROR nym_task::manager  > Polling shutdown failed: channel closed
[2023-08-12][08:48:51] ERROR nym_task::manager  > Polling shutdown failed: channel closed
[2023-08-12][08:48:51] ERROR nym_task::manager  > Polling shutdown failed: channel closed
[2023-08-12][08:48:51] ERROR nym_task::manager  > Assuming this means we should shutdown...
[2023-08-12][08:48:51] INFO  nym_connect::tasks  > Status listener exiting
thread '[2023-08-12][08:48:51] ERROR nym_task::manager  > Assuming this means we should shutdown...
thread 'tokio-runtime-worker[2023-08-12][08:48:51] ERROR nym_task::manager  > Assuming this means we should shutdown...
' panicked at 'called `Result::unwrap()` on an `Err` value: TrySendError { kind: Disconnected }', /home/ubuntu/actions-runner/_work/nym/nym/common/socks5-client-core/src/socks/client.rs:201:18
[2023-08-12][08:48:51] ERROR nym_task::manager  > Polling shutdown failed: channel closed
[2023-08-12][08:48:51] ERROR nym_task::manager  > Polling shutdown failed: channel closed
thread 'thread 'tokio-runtime-worker' panicked at 'thread 'tokio-runtime-workercalled `Result::unwrap()` on an `Err` value: TrySendError { kind: Disconnected }tokio-runtime-worker', ' panicked at '/home/ubuntu/actions-runner/_work/nym/nym/common/socks5-client-core/src/socks/client.rsthread ':tokio-runtime-worker201' panicked at ':[2023-08-12][08:48:51] ERROR nym_task::manager  > Assuming this means we should shutdown...
called `Result::unwrap()` on an `Err` value: TrySendError { kind: Disconnected }[2023-08-12][08:48:51] ERROR nym_task::manager  > Assuming this means we should shutdown...
18', /home/ubuntu/actions-runner/_work/nym/nym/common/socks5-client-core/src/socks/client.rs:tokio-runtime-worker201:' panicked at 'called `Result::unwrap()` on an `Err` value: TrySendError { kind: Disconnected }', /home/ubuntu/actions-runner/_work/nym/nym/common/socks5-client-core/src/socks/client.rs:201:18

' panicked at '[2023-08-12][08:48:51] ERROR nym_task::manager  > Polling shutdown failed: channel closed
called `Result::unwrap()` on an `Err` value: TrySendError { kind: Disconnected }', /home/ubuntu/actions-runner/_work/nym/nym/common/socks5-client-core/src/socks/client.rs:20118:18

called `Result::unwrap()` on an `Err` value: TrySendError { kind: Disconnected }', /home/ubuntu/actions-runner/_work/nym/nym/common/socks5-client-core/src/socks/client.rs:201:18
[2023-08-12][08:48:51] ERROR nym_task::manager  > Assuming this means we should shutdown...
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: TrySendError { kind: Disconnected }', /home/ubuntu/actions-runner/_work/nym/nym/common/socks5-client-core/src/socks/client.rs:201:18
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: TrySendError { kind: Disconnected }', /home/ubuntu/actions-runner/_work/nym/nym/common/socks5-client-core/src/socks/client.rs:201:18
thread 'thread 'tokio-runtime-workertokio-runtime-worker' panicked at '' panicked at 'called `Result::unwrap()` on an `Err` value: TrySendError { kind: Disconnected }', /home/ubuntu/actions-runner/_work/nym/nym/common/socks5-client-core/src/socks/client.rs:called `Result::unwrap()` on an `Err` value: TrySendError { kind: Disconnected }thread '', thread 'tokio-runtime-workerthread '' panicked at 'thread 'tokio-runtime-workercalled `Result::unwrap()` on an `Err` value: TrySendError { kind: Disconnected }tokio-runtime-worker' panicked at '' panicked at 'called `Result::unwrap()` on an `Err` value: TrySendError { kind: Disconnected }', thread 'called `Result::unwrap()` on an `Err` value: TrySendError { kind: Disconnected }', ', /home/ubuntu/actions-runner/_work/nym/nym/common/socks5-client-core/src/socks/client.rstokio-runtime-worker/home/ubuntu/actions-runner/_work/nym/nym/common/socks5-client-core/src/socks/client.rs/home/ubuntu/actions-runner/_work/nym/nym/common/socks5-client-core/src/socks/client.rs:' panicked at '::201called `Result::unwrap()` on an `Err` value: TrySendError { kind: Disconnected }201201:201', ::1818/home/ubuntu/actions-runner/_work/nym/nym/common/socks5-client-core/src/socks/client.rstokio-runtime-worker18:

:18thread '/home/ubuntu/actions-runner/_work/nym/nym/common/socks5-client-core/src/socks/client.rs
201' panicked at 'called `Result::unwrap()` on an `Err` value: TrySendError { kind: Disconnected }', /home/ubuntu/actions-runner/_work/nym/nym/common/socks5-client-core/src/socks/client.rs:
201:18tokio-runtime-worker
' panicked at ':thread ':201tokio-runtime-worker18' panicked at ':called `Result::unwrap()` on an `Err` value: TrySendError { kind: Disconnected }called `Result::unwrap()` on an `Err` value: TrySendError { kind: Disconnected }
18', thread '
/home/ubuntu/actions-runner/_work/nym/nym/common/socks5-client-core/src/socks/client.rs', :thread '201tokio-runtime-worker:tokio-runtime-worker' panicked at 'thread '18called `Result::unwrap()` on an `Err` value: TrySendError { kind: Disconnected }
tokio-runtime-worker/home/ubuntu/actions-runner/_work/nym/nym/common/socks5-client-core/src/socks/client.rs:201' panicked at ':thread '18', tokio-runtime-workercalled `Result::unwrap()` on an `Err` value: TrySendError { kind: Disconnected }thread '
' panicked at '/home/ubuntu/actions-runner/_work/nym/nym/common/socks5-client-core/src/socks/client.rstokio-runtime-workercalled `Result::unwrap()` on an `Err` value: TrySendError { kind: Disconnected }:thread '' panicked at '', 201tokio-runtime-workercalled `Result::unwrap()` on an `Err` value: TrySendError { kind: Disconnected }/home/ubuntu/actions-runner/_work/nym/nym/common/socks5-client-core/src/socks/client.rs:' panicked at '', :/home/ubuntu/actions-runner/_work/nym/nym/common/socks5-client-core/src/socks/client.rs18called `Result::unwrap()` on an `Err` value: TrySendError { kind: Disconnected }201:
', :201/home/ubuntu/actions-runner/_work/nym/nym/common/socks5-client-core/src/socks/client.rs18::
18201thread '
:tokio-runtime-worker18' panicked at '
called `Result::unwrap()` on an `Err` value: TrySendError { kind: Disconnected }', thread '/home/ubuntu/actions-runner/_work/nym/nym/common/socks5-client-core/src/socks/client.rstokio-runtime-worker:' panicked at '201called `Result::unwrap()` on an `Err` value: TrySendError { kind: Disconnected }:', 18/home/ubuntu/actions-runner/_work/nym/nym/common/socks5-client-core/src/socks/client.rs
thread ':tokio-runtime-worker201' panicked at ':called `Result::unwrap()` on an `Err` value: TrySendError { kind: Disconnected }18thread '', 
thread 'tokio-runtime-worker/home/ubuntu/actions-runner/_work/nym/nym/common/socks5-client-core/src/socks/client.rstokio-runtime-worker' panicked at ':' panicked at 'called `Result::unwrap()` on an `Err` value: TrySendError { kind: Disconnected }201called `Result::unwrap()` on an `Err` value: TrySendError { kind: Disconnected }', :/home/ubuntu/actions-runner/_work/nym/nym/common/socks5-client-core/src/socks/client.rs', 18:/home/ubuntu/actions-runner/_work/nym/nym/common/socks5-client-core/src/socks/client.rs
201::20118:thread '
thread '18tokio-runtime-workertokio-runtime-worker
' panicked at '' panicked at 'called `Result::unwrap()` on an `Err` value: TrySendError { kind: Disconnected }called `Result::unwrap()` on an `Err` value: TrySendError { kind: Disconnected }', thread '', /home/ubuntu/actions-runner/_work/nym/nym/common/socks5-client-core/src/socks/client.rstokio-runtime-worker/home/ubuntu/actions-runner/_work/nym/nym/common/socks5-client-core/src/socks/client.rs:' panicked at 'thread ':201called `Result::unwrap()` on an `Err` value: TrySendError { kind: Disconnected }thread 'tokio-runtime-worker201:', tokio-runtime-worker' panicked at ':18/home/ubuntu/actions-runner/_work/nym/nym/common/socks5-client-core/src/socks/client.rs' panicked at 'called `Result::unwrap()` on an `Err` value: TrySendError { kind: Disconnected }18
:called `Result::unwrap()` on an `Err` value: TrySendError { kind: Disconnected }', 
201', /home/ubuntu/actions-runner/_work/nym/nym/common/socks5-client-core/src/socks/client.rs:/home/ubuntu/actions-runner/_work/nym/nym/common/socks5-client-core/src/socks/client.rs:18:201
201::1818

thread 'thread 'tokio-runtime-workertokio-runtime-worker' panicked at '' panicked at 'called `Result::unwrap()` on an `Err` value: TrySendError { kind: Disconnected }called `Result::unwrap()` on an `Err` value: TrySendError { kind: Disconnected }', ', /home/ubuntu/actions-runner/_work/nym/nym/common/socks5-client-core/src/socks/client.rsthread '/home/ubuntu/actions-runner/_work/nym/nym/common/socks5-client-core/src/socks/client.rs:tokio-runtime-workerthread ':201' panicked at 'thread 'tokio-runtime-worker201:called `Result::unwrap()` on an `Err` value: TrySendError { kind: Disconnected }tokio-runtime-worker' panicked at ':1818', ' panicked at 'called `Result::unwrap()` on an `Err` value: TrySendError { kind: Disconnected }

/home/ubuntu/actions-runner/_work/nym/nym/common/socks5-client-core/src/socks/client.rscalled `Result::unwrap()` on an `Err` value: TrySendError { kind: Disconnected }', ', :/home/ubuntu/actions-runner/_work/nym/nym/common/socks5-client-core/src/socks/client.rs/home/ubuntu/actions-runner/_work/nym/nym/common/socks5-client-core/src/socks/client.rs201:::20118201:
:1818

thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: TrySendError { kind: Disconnected }', /home/ubuntu/actions-runner/_work/nym/nym/common/socks5-client-core/src/socks/client.rs:201:thread '18tokio-runtime-worker
' panicked at 'thread 'thread 'called `Result::unwrap()` on an `Err` value: TrySendError { kind: Disconnected }tokio-runtime-workerthread 'tokio-runtime-worker', ' panicked at '/home/ubuntu/actions-runner/_work/nym/nym/common/socks5-client-core/src/socks/client.rstokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: TrySendError { kind: Disconnected }:' panicked at 'called `Result::unwrap()` on an `Err` value: TrySendError { kind: Disconnected }', 201called `Result::unwrap()` on an `Err` value: TrySendError { kind: Disconnected }thread '', /home/ubuntu/actions-runner/_work/nym/nym/common/socks5-client-core/src/socks/client.rs:', tokio-runtime-worker/home/ubuntu/actions-runner/_work/nym/nym/common/socks5-client-core/src/socks/client.rs/home/ubuntu/actions-runner/_work/nym/nym/common/socks5-client-core/src/socks/client.rs:18' panicked at '::201
called `Result::unwrap()` on an `Err` value: TrySendError { kind: Disconnected }201201:', ::18/home/ubuntu/actions-runner/_work/nym/nym/common/socks5-client-core/src/socks/client.rs1818
:

201:18
thread 'tokio-runtime-workerthread '' panicked at 'tokio-runtime-workercalled `Result::unwrap()` on an `Err` value: TrySendError { kind: Disconnected }' panicked at 'thread 'thread '', called `Result::unwrap()` on an `Err` value: TrySendError { kind: Disconnected }thread 'tokio-runtime-workertokio-runtime-worker/home/ubuntu/actions-runner/_work/nym/nym/common/socks5-client-core/src/socks/client.rs', tokio-runtime-worker' panicked at '' panicked at '' panicked at ':/home/ubuntu/actions-runner/_work/nym/nym/common/socks5-client-core/src/socks/client.rscalled `Result::unwrap()` on an `Err` value: TrySendError { kind: Disconnected }called `Result::unwrap()` on an `Err` value: TrySendError { kind: Disconnected }called `Result::unwrap()` on an `Err` value: TrySendError { kind: Disconnected }201:', 201', ', :/home/ubuntu/actions-runner/_work/nym/nym/common/socks5-client-core/src/socks/client.rs:/home/ubuntu/actions-runner/_work/nym/nym/common/socks5-client-core/src/socks/client.rs/home/ubuntu/actions-runner/_work/nym/nym/common/socks5-client-core/src/socks/client.rs18:18::
201
201201::1818

:18
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: TrySendError { kind: Disconnected }', thread '/home/ubuntu/actions-runner/_work/nym/nym/common/socks5-client-core/src/socks/client.rsthread 'thread 'tokio-runtime-workerthread ':tokio-runtime-workertokio-runtime-worker' panicked at 'tokio-runtime-worker201' panicked at '' panicked at 'called `Result::unwrap()` on an `Err` value: TrySendError { kind: Disconnected }' panicked at ':called `Result::unwrap()` on an `Err` value: TrySendError { kind: Disconnected }called `Result::unwrap()` on an `Err` value: TrySendError { kind: Disconnected }', called `Result::unwrap()` on an `Err` value: TrySendError { kind: Disconnected }18', ', /home/ubuntu/actions-runner/_work/nym/nym/common/socks5-client-core/src/socks/client.rs/home/ubuntu/actions-runner/_work/nym/nym/common/socks5-client-core/src/socks/client.rs', 
/home/ubuntu/actions-runner/_work/nym/nym/common/socks5-client-core/src/socks/client.rs::/home/ubuntu/actions-runner/_work/nym/nym/common/socks5-client-core/src/socks/client.rs:201201:201::201:1818:18


18thread '
tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: TrySendError { kind: Disconnected }', /home/ubuntu/actions-runner/_work/nym/nym/common/socks5-client-core/src/socks/client.rs:201:18
thread 'thread 'tokio-runtime-workertokio-runtime-worker' panicked at '' panicked at 'thread 'called `Result::unwrap()` on an `Err` value: TrySendError { kind: Disconnected }called `Result::unwrap()` on an `Err` value: TrySendError { kind: Disconnected }tokio-runtime-worker', thread '', ' panicked at '/home/ubuntu/actions-runner/_work/nym/nym/common/socks5-client-core/src/socks/client.rstokio-runtime-worker/home/ubuntu/actions-runner/_work/nym/nym/common/socks5-client-core/src/socks/client.rscalled `Result::unwrap()` on an `Err` value: TrySendError { kind: Disconnected }thread ':' panicked at ':', tokio-runtime-worker/home/ubuntu/actions-runner/_work/nym/nym/common/socks5-client-core/src/socks/client.rs201called `Result::unwrap()` on an `Err` value: TrySendError { kind: Disconnected }201' panicked at '::', :called `Result::unwrap()` on an `Err` value: TrySendError { kind: Disconnected }20118/home/ubuntu/actions-runner/_work/nym/nym/common/socks5-client-core/src/socks/client.rs18', :/home/ubuntu/actions-runner/_work/nym/nym/common/socks5-client-core/src/socks/client.rs
:
18:201
201::1818

thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: TrySendError { kind: Disconnected }', thread '/home/ubuntu/actions-runner/_work/nym/nym/common/socks5-client-core/src/socks/client.rsthread 'tokio-runtime-worker:tokio-runtime-worker' panicked at '201' panicked at 'called `Result::unwrap()` on an `Err` value: TrySendError { kind: Disconnected }:', 18/home/ubuntu/actions-runner/_work/nym/nym/common/socks5-client-core/src/socks/client.rscalled `Result::unwrap()` on an `Err` value: TrySendError { kind: Disconnected }
:', 201/home/ubuntu/actions-runner/_work/nym/nym/common/socks5-client-core/src/socks/client.rsthread ':thread ':tokio-runtime-worker18tokio-runtime-worker201' panicked at '
' panicked at ':called `Result::unwrap()` on an `Err` value: TrySendError { kind: Disconnected }thread '18', tokio-runtime-worker
' panicked at '/home/ubuntu/actions-runner/_work/nym/nym/common/socks5-client-core/src/socks/client.rscalled `Result::unwrap()` on an `Err` value: TrySendError { kind: Disconnected }:thread '', 201tokio-runtime-worker/home/ubuntu/actions-runner/_work/nym/nym/common/socks5-client-core/src/socks/client.rs:' panicked at ':called `Result::unwrap()` on an `Err` value: TrySendError { kind: Disconnected }18thread 'thread '' panicked at 'tokio-runtime-workertokio-runtime-worker' panicked at '', called `Result::unwrap()` on an `Err` value: TrySendError { kind: Disconnected }' panicked at 'called `Result::unwrap()` on an `Err` value: TrySendError { kind: Disconnected }', /home/ubuntu/actions-runner/_work/nym/nym/common/socks5-client-core/src/socks/client.rs', called `Result::unwrap()` on an `Err` value: TrySendError { kind: Disconnected }/home/ubuntu/actions-runner/_work/nym/nym/common/socks5-client-core/src/socks/client.rs:/home/ubuntu/actions-runner/_work/nym/nym/common/socks5-client-core/src/socks/client.rs', :201/home/ubuntu/actions-runner/_work/nym/nym/common/socks5-client-core/src/socks/client.rs201::::1820120118
::18
18

thread 'thread 'tokio-runtime-workertokio-runtime-worker' panicked at '' panicked at 'called `Result::unwrap()` on an `Err` value: TrySendError { kind: Disconnected }thread 'called `Result::unwrap()` on an `Err` value: TrySendError { kind: Disconnected }', tokio-runtime-worker', ' panicked at '/home/ubuntu/actions-runner/_work/nym/nym/common/socks5-client-core/src/socks/client.rs/home/ubuntu/actions-runner/_work/nym/nym/common/socks5-client-core/src/socks/client.rscalled `Result::unwrap()` on an `Err` value: TrySendError { kind: Disconnected }::', thread '201201/home/ubuntu/actions-runner/_work/nym/nym/common/socks5-client-core/src/socks/client.rstokio-runtime-worker:::' panicked at '1818201called `Result::unwrap()` on an `Err` value: TrySendError { kind: Disconnected }
', 
:/home/ubuntu/actions-runner/_work/nym/nym/common/socks5-client-core/src/socks/client.rs18:
201:18
thread 'thread 'tokio-runtime-workertokio-runtime-worker' panicked at '' panicked at 'called `Result::unwrap()` on an `Err` value: TrySendError { kind: Disconnected }called `Result::unwrap()` on an `Err` value: TrySendError { kind: Disconnected }', ', thread '/home/ubuntu/actions-runner/_work/nym/nym/common/socks5-client-core/src/socks/client.rs/home/ubuntu/actions-runner/_work/nym/nym/common/socks5-client-core/src/socks/client.rstokio-runtime-worker::' panicked at '201called `Result::unwrap()` on an `Err` value: TrySendError { kind: Disconnected }201:thread '', :18tokio-runtime-worker/home/ubuntu/actions-runner/_work/nym/nym/common/socks5-client-core/src/socks/client.rs18
' panicked at ':
called `Result::unwrap()` on an `Err` value: TrySendError { kind: Disconnected }201', :/home/ubuntu/actions-runner/_work/nym/nym/common/socks5-client-core/src/socks/client.rs18:
201:18
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: TrySendError { kind: Disconnected }thread '', tokio-runtime-worker/home/ubuntu/actions-runner/_work/nym/nym/common/socks5-client-core/src/socks/client.rs' panicked at ':called `Result::unwrap()` on an `Err` value: TrySendError { kind: Disconnected }201', :/home/ubuntu/actions-runner/_work/nym/nym/common/socks5-client-core/src/socks/client.rs18:thread '
201tokio-runtime-worker:' panicked at '18called `Result::unwrap()` on an `Err` value: TrySendError { kind: Disconnected }
', /home/ubuntu/actions-runner/_work/nym/nym/common/socks5-client-core/src/socks/client.rs:201:thread '18tokio-runtime-worker
thread '' panicked at 'tokio-runtime-workercalled `Result::unwrap()` on an `Err` value: TrySendError { kind: Disconnected }' panicked at '', called `Result::unwrap()` on an `Err` value: TrySendError { kind: Disconnected }/home/ubuntu/actions-runner/_work/nym/nym/common/socks5-client-core/src/socks/client.rs', :/home/ubuntu/actions-runner/_work/nym/nym/common/socks5-client-core/src/socks/client.rs201:thread ':201tokio-runtime-worker18' panicked at '
:called `Result::unwrap()` on an `Err` value: TrySendError { kind: Disconnected }thread '18', tokio-runtime-worker
/home/ubuntu/actions-runner/_work/nym/nym/common/socks5-client-core/src/socks/client.rs' panicked at ':called `Result::unwrap()` on an `Err` value: TrySendError { kind: Disconnected }201', :/home/ubuntu/actions-runner/_work/nym/nym/common/socks5-client-core/src/socks/client.rs18:
201:18
thread 'thread 'tokio-runtime-workertokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: TrySendError { kind: Disconnected }' panicked at '', called `Result::unwrap()` on an `Err` value: TrySendError { kind: Disconnected }/home/ubuntu/actions-runner/_work/nym/nym/common/socks5-client-core/src/socks/client.rs', :/home/ubuntu/actions-runner/_work/nym/nym/common/socks5-client-core/src/socks/client.rs201::20118:
18
called `Result::unwrap()` on an `Err` value: TrySendError { kind: Disconnected }', /home/ubuntu/actions-runner/_work/nym/nym/common/socks5-client-core/src/socks/client.rs:201:18
201:', 18/home/ubuntu/actions-runner/_work/nym/nym/common/socks5-client-core/src/socks/client.rs
:201:18

[2023-08-12][08:48:51] ERROR nym_connect::tasks  > SOCKS5 proxy failed: Task halted unexpectedly
[2023-08-12][08:48:51] INFO  nym_connect::tasks  > SOCKS5 task reported error: Task halted unexpectedly
[2023-08-12][08:48:51] INFO  nym_connect::state  > Disconnected

```

**Steps to Reproduce**
- Run nym-connect
- close the lid 
- wait until computer enters suspend mode
- reopen the lid
- wait until network is available

**Which area of Nym were you using?**
 - Application:Nym connect 1.1.16
 - OS: Ubuntu 22.04.3 LTS

**Comment by tommyv1987** [comment]
Focus has gone into the VPN product now, closing ticket
