### ISSUE TITLE
nymproject+mix-fetch-node-commonjs@1.2.4-rc.1 has missing `fake-indexeddb` dependency

### ISSUE THREAD

**Issue by CedarMist** [nymtech/nym#4287]
**Describe the issue**
When installing mix-fetch-node-commonjs 

**Expected behaviour**
The project should work 'out of the box'

**Stack Traces**

```
     Error: Cannot find module 'fake-indexeddb'
Require stack:
- /src/demo-nym/backend/node_modules/.pnpm/@nymproject+mix-fetch-node-commonjs@1.2.4-rc.1/node_modules/@nymproject/mix-fetch-node-commonjs/web-worker-0.js
      at Module._resolveFilename (node:internal/modules/cjs/loader:1134:15)
      at Module._load (node:internal/modules/cjs/loader:975:27)
      at Module.require (node:internal/modules/cjs/loader:1225:19)
      at require (node:internal/modules/helpers:177:18)
      at /src/demo-nym/backend/node_modules/.pnpm/@nymproject+mix-fetch-node-commonjs@1.2.4-rc.1/node_modules/@nymproject/mix-fetch-node-commonjs/web-worker-0.js:25:22
      at Object.<anonymous> (node_modules/.pnpm/@nymproject+mix-fetch-node-commonjs@1.2.4-rc.1/node_modules/@nymproject/mix-fetch-node-commonjs/web-worker-0.js:17882:3)
      at Module._compile (node:internal/modules/cjs/loader:1356:14)
      at Module._extensions..js (node:internal/modules/cjs/loader:1414:10)
      at Module.load (node:internal/modules/cjs/loader:1197:32)
      at Module._load (node:internal/modules/cjs/loader:1013:12)
```

**Steps to Reproduce**
https://gist.github.com/CedarMist/611a54a2a6ea3377278ec4b4167b5fd8

Add packages:

 * "@nymproject/mix-fetch-node-commonjs": "1.2.4-rc.1",
 * "web3-types": "^1.3.1"
 * "web3-errors": "^1.1.4",

Run code, see stacktrace.

Adding the following dependency fixed this, and it works as expected:

 * "fake-indexeddb": "^5.0.1",

**Comment by tommyv1987** [comment]
Hi @CedarMist we're also aware of this too and the work around is to install the missing package, as mentioned above. I'm going to close this ticket as we already have it noted on our dev board, and we're looking to allocate more time to the SDK development shortly. Thank you for raising the issue, we appreciate it.

**Comment by tommyv1987** [comment]
@CedarMist this is the ticket here: https://github.com/nymtech/nym/issues/3385
