### ISSUE TITLE
Mixnode crash

### ISSUE THREAD

**Issue by sgeisler** [nymtech/nym#486]
I just noticed that my nym mixnode had crashed, I included some of the logs leading up to the crash below:

```
 2020-12-02T12:02:28.847 DEBUG nym_mixnode::node::metrics                         > Since last metrics report mixed 66 packets!
 2020-12-02T12:02:28.847 DEBUG nym_mixnode::node::metrics                         > Since last metrics report received 66 packets
 2020-12-02T12:02:28.847 INFO  nym_mixnode::node::metrics                         > Since startup mixed 469899 packets!
 2020-12-02T12:02:28.847 DEBUG nym_mixnode::node::metrics                         > Since startup received 469906 packets
 2020-12-02T12:02:32.070 DEBUG mixnode_common::cached_packet_processor::processor > Other thread has already cached keys for this secret!
 2020-12-02T12:02:37.979 DEBUG mixnode_common::cached_packet_processor::processor > Other thread has already cached keys for this secret!
 2020-12-02T12:02:38.295 DEBUG mixnode_common::cached_packet_processor::processor > Other thread has already cached keys for this secret!
 2020-12-02T12:02:41.016 DEBUG nym_mixnode::node::metrics                         > sent metrics information
 2020-12-02T12:02:51.989 DEBUG mixnode_common::cached_packet_processor::processor > Other thread has already cached keys for this secret!
 2020-12-02T12:02:53.594 DEBUG mixnode_common::cached_packet_processor::processor > Other thread has already cached keys for this secret!
 2020-12-02T12:02:58.495 DEBUG mixnode_common::cached_packet_processor::processor > Other thread has already cached keys for this secret!
 2020-12-02T12:03:02.562 DEBUG mixnode_common::cached_packet_processor::processor > Other thread has already cached keys for this secret!
 2020-12-02T12:03:03.156 DEBUG mixnode_common::cached_packet_processor::processor > Other thread has already cached keys for this secret!
 2020-12-02T12:03:11.385 DEBUG mixnode_common::cached_packet_processor::processor > Other thread has already cached keys for this secret!
 2020-12-02T12:03:12.016 DEBUG nym_mixnode::node::metrics                         > Since last metrics report mixed 95 packets!
 2020-12-02T12:03:12.016 DEBUG nym_mixnode::node::metrics                         > Since last metrics report received 95 packets
 2020-12-02T12:03:15.220 DEBUG mixnode_common::cached_packet_processor::processor > Other thread has already cached keys for this secret!
 2020-12-02T12:03:15.354 DEBUG nym_mixnode::node::metrics                         > sent metrics information
 2020-12-02T12:03:20.867 DEBUG mixnode_common::cached_packet_processor::processor > Other thread has already cached keys for this secret!
 2020-12-02T12:03:21.005 DEBUG mixnode_common::cached_packet_processor::processor > Other thread has already cached keys for this secret!
 2020-12-02T12:03:27.550 DEBUG mixnode_common::cached_packet_processor::processor > Other thread has already cached keys for this secret!
 2020-12-02T12:03:34.365 DEBUG mixnode_common::cached_packet_processor::processor > Other thread has already cached keys for this secret!
 2020-12-02T12:03:37.328 DEBUG mixnode_common::cached_packet_processor::processor > Other thread has already cached keys for this secret!
thread 'tokio-runtime-worker' panicked at 'index out of bounds: the len is 8 but the index is 8', /home/seb/.cargo/registry/src/github.com-1ecc6299db9ec823/dashmap-4.0.0-rc6/src/spec/fallback.rs:226:24
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1076
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1537
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:198
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:218
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:486
  11: rust_begin_unwind
             at src/libstd/panicking.rs:388
  12: core::panicking::panic_fmt
             at src/libcore/panicking.rs:101
  13: core::panicking::panic_bounds_check
             at src/libcore/panicking.rs:73
  14: <dashmap::spec::fallback::Table<K,V,S> as dashmap::table::Table<K,V,S>>::get
  15: mixnode_common::cached_packet_processor::processor::CachedPacketProcessor::process_received
  16: nym_mixnode::node::listener::connection_handler::ConnectionHandler::handle_received_packet
  17: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  18: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by tommyv1987** [comment]
Hi @sgeisler, 

Thank you for raising this issue, sorry for the length of time it has taken to get in touch with you.

We're currently in the process of reviewing some of our issues, and we have a designated template to address issues.

Have you run into this problem since logging the issue?

Thank you for being patient.

**Comment by tommyv1987** [comment]
Closing ticket, as no response from raiser. mix-node versions have is now at `v0.12.1` so this will be outdated.
