### ISSUE TITLE
nymd start request blocks error

### ISSUE THREAD

**Issue by btcnash** [nymtech/nym#616]
1:57PM INF indexed block height=11455 module=txindex
panic: Failed to process committed block (11456:5E8E48BE40C96E9D726C354A794EC733261F8B8A304BE96935FEAA3C86271E25): wrong Block.Header.AppHash.  Expected 2C085A9CB4AD40F759CBF6A1A5F45DAF7B7087B5D6B45FAA3D7DB1C1E1DD42F3, got 3F89CEA021DB28CDC6DE5CB4CAB4B87DB18DAD305518B1E89C285CB14024853F

goroutine 194 [running]:
github.com/tendermint/tendermint/blockchain/v0.(*BlockchainReactor).poolRoutine(0xc000cd96c0, 0x0)
	github.com/tendermint/tendermint@v0.34.10/blockchain/v0/reactor.go:401 +0x15bf
created by github.com/tendermint/tendermint/blockchain/v0.(*BlockchainReactor).OnStart
	github.com/tendermint/tendermint@v0.34.10/blockchain/v0/reactor.go:110 +0x8c
root@localhost:~/.nymd/config#

**Comment by btcnash** [comment]
```
5:50PM INF Replay: BlockPart height=11455 module=consensus peer=e7163ea63219504344c669164d083f52434f382b round=0
5:50PM INF Replay: Vote blockID={"hash":"5E8E48BE40C96E9D726C354A794EC733261F8B8A304BE96935FEAA3C86271E25","parts":{"hash":"C665A7223DF2854C7D49A1C70C4DBD0A6BF626789B18D949B9A9767AE1D6F56E","total":1}} height=11456 module=consensus peer=e7163ea63219504344c669164d083f52434f382b round=0 type=2
5:50PM INF Replay: BlockPart height=11456 module=consensus peer=e7163ea63219504344c669164d083f52434f382b round=0
5:50PM INF received complete proposal block hash=5E8E48BE40C96E9D726C354A794EC733261F8B8A304BE96935FEAA3C86271E25 height=11456 module=consensus
panic: +2/3 committed an invalid block: wrong Block.Header.AppHash.  Expected 2C085A9CB4AD40F759CBF6A1A5F45DAF7B7087B5D6B45FAA3D7DB1C1E1DD42F3, got 3F89CEA021DB28CDC6DE5CB4CAB4B87DB18DAD305518B1E89C285CB14024853F

goroutine 1 [running]:
github.com/tendermint/tendermint/consensus.(*State).finalizeCommit(0xc000f36e00, 0x2cc0)
	github.com/tendermint/tendermint@v0.34.10/consensus/state.go:1575 +0x1385
github.com/tendermint/tendermint/consensus.(*State).tryFinalizeCommit(0xc000f36e00, 0x2cc0)
	github.com/tendermint/tendermint@v0.34.10/consensus/state.go:1546 +0x428
github.com/tendermint/tendermint/consensus.(*State).addProposalBlockPart(0xc000f36e00, 0xc0011d5e78, 0xc004bf6d20, 0x28, 0xc000283c00, 0x15, 0x1f4)
	github.com/tendermint/tendermint@v0.34.10/consensus/state.go:1919 +0x7c5
github.com/tendermint/tendermint/consensus.(*State).handleMsg(0xc000f36e00, 0x20e3800, 0xc0011d5e78, 0xc004bf6d20, 0x28)
	github.com/tendermint/tendermint@v0.34.10/consensus/state.go:820 +0x5cc
github.com/tendermint/tendermint/consensus.(*State).readReplayMessage(0xc000f36e00, 0xc004bf9410, 0x0, 0x0, 0x0, 0x0)
	github.com/tendermint/tendermint@v0.34.10/consensus/replay.go:81 +0x3d8
github.com/tendermint/tendermint/consensus.(*State).catchupReplay(0xc000f36e00, 0x2cc0, 0x0, 0x0)
	github.com/tendermint/tendermint@v0.34.10/consensus/replay.go:160 +0x4b9
github.com/tendermint/tendermint/consensus.(*State).OnStart(0xc000f36e00, 0xc000ee6540, 0x16)
	github.com/tendermint/tendermint@v0.34.10/consensus/state.go:314 +0xa8
github.com/tendermint/tendermint/libs/service.(*BaseService).Start(0xc000f36e00, 0x1f04600, 0xc0003eed80)
	github.com/tendermint/tendermint@v0.34.10/libs/service/service.go:140 +0x322
github.com/tendermint/tendermint/consensus.(*Reactor).OnStart(0xc0003eed80, 0xc00011dd60, 0x1a)
	github.com/tendermint/tendermint@v0.34.10/consensus/reactor.go:83 +0x145
github.com/tendermint/tendermint/libs/service.(*BaseService).Start(0xc0003eed80, 0x0, 0x0)
	github.com/tendermint/tendermint@v0.34.10/libs/service/service.go:140 +0x322
github.com/tendermint/tendermint/p2p.(*Switch).OnStart(0xc000f03320, 0xc00011da80, 0x1b)
	github.com/tendermint/tendermint@v0.34.10/p2p/switch.go:226 +0xb8
github.com/tendermint/tendermint/libs/service.(*BaseService).Start(0xc000f03320, 0xc000224400, 0x28)
	github.com/tendermint/tendermint@v0.34.10/libs/service/service.go:140 +0x322
github.com/tendermint/tendermint/node.(*Node).OnStart(0xc000300b00, 0xc000ee6090, 0x15)
	github.com/tendermint/tendermint@v0.34.10/node/node.go:919 +0x2ba
github.com/tendermint/tendermint/libs/service.(*BaseService).Start(0xc000300b00, 0x1cc6c18, 0x1e)
	github.com/tendermint/tendermint@v0.34.10/libs/service/service.go:140 +0x322
github.com/cosmos/cosmos-sdk/server.startInProcess(0xc000eb11e0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x2127740, 0xc000e45980, ...)
	github.com/cosmos/cosmos-sdk@v0.42.4/server/start.go:259 +0x60e
github.com/cosmos/cosmos-sdk/server.StartCmd.func2(0xc000e98280, 0x2d86ff8, 0x0, 0x0, 0x0, 0x0)
	github.com/cosmos/cosmos-sdk@v0.42.4/server/start.go:120 +0x1c8
github.com/spf13/cobra.(*Command).execute(0xc000e98280, 0x2d86ff8, 0x0, 0x0, 0xc000e98280, 0x2d86ff8)
	github.com/spf13/cobra@v1.1.3/command.go:852 +0x472
github.com/spf13/cobra.(*Command).ExecuteC(0xc000e4c500, 0x1c9c217, 0x2, 0xc000e1c760)
	github.com/spf13/cobra@v1.1.3/command.go:960 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.1.3/command.go:897
github.com/spf13/cobra.(*Command).ExecuteContext(...)
	github.com/spf13/cobra@v1.1.3/command.go:890
main.Execute(0xc000e4c500, 0xc000e1c760, 0xb, 0x213a098, 0xc000e25560)
	github.com/CosmWasm/wasmd/cmd/wasmd/execute.go:38 +0x26f
main.main()
	github.com/CosmWasm/wasmd/cmd/wasmd/main.go:13 +0x45

```

**Comment by iranzo** [comment]
Duplicate of #596 ?

**Comment by tommyv1987** [comment]
Going to close this ticket as this is somewhat outdated and we're no longer running this version of wasmd on mainnetor our test environments.
