### ISSUE TITLE
[Issue] `nym-client` requires multiple attempts to run a server

### ISSUE THREAD

**Issue by pwnfoo** [nymtech/nym#869]
**Describe the issue**
A clear and concise description of what the issue is...

I was trying to setup `nym-client` to test out sending traffic through mix node. After installation and init, the node refused to run multiple times with the following error messages : 

```
 2021-11-03T03:17:08.426Z INFO  nym_client::client > Starting nym client
 2021-11-03T03:17:08.616Z INFO  nym_client::client > Obtaining initial network topology
 2021-11-03T03:17:10.486Z WARN  topology           > Mix 2q2ekAP2WuTzuFWur6Rj9x64cLKHoA1Lv4yeoebQGUpZ is malformed - failed to convert mixnode due to invalid address  95.179.145.87 - failed to lookup address information: Name or service not known
 2021-11-03T03:17:10.489Z WARN  topology           > Mix 3ezghuf7rDoceMtUMCFtum72KPm6XUgpt95oF8niQLk6 is malformed - failed to convert mixnode due to invalid identity key - malformed bytes - signature error
 2021-11-03T03:17:10.519Z WARN  topology           > Mix Cbe8JLYFCtbUYvgrkiZtiniqDNGUzzG9hiDwQjfyjCrP is malformed - failed to convert mixnode due to invalid address  88.99.35.245 - failed to lookup address information: Name or service not known
 2021-11-03T03:17:10.522Z WARN  topology           > Mix DC6PZiTronXyAGJDobw32LSiVTX5eDW32JB7JudfhkS7 is malformed - failed to convert mixnode due to invalid address  68.183.0.34 - failed to lookup address information: Name or service not known
 2021-11-03T03:17:10.523Z WARN  topology           > Mix DT82Bek8WeKnaAUifaSRbKzNvFhSZUw7nWZwT6HNtJ38 is malformed - failed to convert mixnode due to invalid address  45.63.90.199 - failed to lookup address information: Name or service not known
 2021-11-03T03:17:10.540Z WARN  topology           > Mix edwMBesmAaoMQZZMeJP8ntvHSPiWjtqq4Gj3QmD9fBD is malformed - failed to convert mixnode due to invalid address  161.35.149.228 - failed to lookup address information: Name or service not known
 2021-11-03T03:17:10.541Z WARN  topology           > Mix foo is malformed - failed to convert mixnode due to invalid identity key - malformed bytes - signature error
 2021-11-03T03:17:10.542Z WARN  topology           > Mix wDrheh19H8EV5SXj1DVro9TJkLhooHZ5FwwpQ2P7S5i is malformed - failed to convert mixnode due to invalid address [2a01:4f9:c011:3c18::1]:1789 - failed to lookup address information: Name or service not known
thread 'main' panicked at 'The current network topology seem to be insufficient to route any packets through- check if enough nodes and a gateway are online', clients/native/src/client/mod.rs:234:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Aborted (core dumped)
```
and

```
 2021-11-03T03:22:21.435Z INFO  nym_client::client > Starting nym client
 2021-11-03T03:22:21.485Z INFO  nym_client::client > Obtaining initial network topology
thread 'main' panicked at 'The current network topology seem to be insufficient to route any packets through- check if enough nodes and a gateway are online', clients/native/src/client/mod.rs:234:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Aborted (core dumped)
```
After multiple failed attempts to run the node, the node is finally able to connect to the mixnodes and starts up the socket.

**Expected behaviour**

`nym-client` must not crash during these exceptions and must continue to make connections

**Steps to Reproduce**
Steps to reproduce the behaviour, if you're familiar with BDD syntax, please write it in this style:
- Install nym-client
- `nym-client init --id xxx`
- `nym-client run --id xxx` <-- fails with the above error

**Which area of Nym were you using?**
 - Application: Client
 - OS: Ubuntu 20.04.3 LTS
 - Version: `Nym Client 0.11.0`

**Comment by tommyv1987** [comment]
hi @pwnfoo 

Thank you for raising this, we have migrated onto our new sandbox environment. We are now running version `v0.12.1` and a lot has changed since the issue was raised. I've tried to replicate your issue, and I'm not able to reproduce it.

If you can try with the latest versions of our releases. That will be great. In the interim, I'm going to close the ticket. If you do have issues, please re-open the ticket.

Thanks,
Tommy
