### ISSUE TITLE
[Issue] NodeJS 17.1.0 and webpack issues causing nym-wallet build to fail on Pop!OS 21.04(Ubuntu)

### ISSUE THREAD

**Issue by gyrusdentatus** [nymtech/nym#914]
**Describe the issue**
On **Pop!OS 21.04** (Ubuntu derivate distro), with the latest **Node.js v17.1.0** there seems to be some issue with the **webpack** and **binary fails to build** properly 
For more details read this ~ week old [post](https://stackoverflow.com/questions/69665222/node-17-0-1-causes-some-error-digital-envelope-routinesunsupported) and the **2nd answer** for more info

![image](https://user-images.githubusercontent.com/33793809/142917481-51f69c52-b35e-4188-885a-e76817c04e39.png)

After **rolling back** to **NodeJS = v16.8.0** as per [docs](https://nymtech.net/docs/0.11.0/nym-apps/wallet) the **problem seemed to be solved** and the **binary launched**; however, **it crashes** after **interacting** with it.

```
hans at pop-os in ~/development/nym/nym-wallet on develop
$ target/release/nym-wallet 

(WebKitWebProcess:117387): Gdk-ERROR **: 19:55:48.430: The program 'WebKitWebProcess' received an X Window System error.
```

**Expected behaviour**
Following the docs and having all the prerequisites installed I was expecting this would go smooth, as it did on MacOS with M1 chip. 

**Steps to Reproduce**
- install the latest NodeJS `nvm install 17` then command `corepack enable` (was just following the official instructions on npm website) and `npm i -g corepack`
- from nym-wallet directory (development branch) `yarn install` and then `yarn build`

**An example:**
- right after `yarn build` happens this:
```
 app:spawn Running "/home/hans/development/nym/nym-wallet/node_modules/@tauri-apps/cli/bin/tauri-cli tauri build" +0ms

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:130:10)
    at BulkUpdateDecorator.hashFactory (/home/hans/development/nym/nym-wallet/node_modules/webpack/lib/util/createHash.js:145:18)
    at BulkUpdateDecorator.update (/home/hans/development/nym/nym-wallet/node_modules/webpack/lib/util/createHash.js:46:50)
    at RawSource.updateHash (/home/hans/development/nym/nym-wallet/node_modules/webpack-sources/lib/RawSource.js:70:8)
    at NormalModule._initBuildHash (/home/hans/development/nym/nym-wallet/node_modules/webpack/lib/NormalModule.js:888:17)
    at handleParseResult (/home/hans/development/nym/nym-wallet/node_modules/webpack/lib/NormalModule.js:954:10)
    at /home/hans/development/nym/nym-wallet/node_modules/webpack/lib/NormalModule.js:1048:4
    at processResult (/home/hans/development/nym/nym-wallet/node_modules/webpack/lib/NormalModule.js:763:11)
    at /home/hans/development/nym/nym-wallet/node_modules/webpack/lib/NormalModule.js:827:5
```
and a bit later

```
Compiling glib v0.14.8
node:internal/crypto/hash:67=======>   ] 669/728: blake3, gobject-...
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:130:10)
    at BulkUpdateDecorator.hashFactory (/home/hans/development/nym/nym-wallet/node_modules/webpack/lib/util/createHash.js:145:18)
    at BulkUpdateDecorator.update (/home/hans/development/nym/nym-wallet/node_modules/webpack/lib/util/createHash.js:46:50)
    at RawSource.updateHash (/home/hans/development/nym/nym-wallet/node_modules/webpack-sources/lib/RawSource.js:70:8)
    at NormalModule._initBuildHash (/home/hans/development/nym/nym-wallet/node_modules/webpack/lib/NormalModule.js:888:17)
    at handleParseResult (/home/hans/development/nym/nym-wallet/node_modules/webpack/lib/NormalModule.js:954:10)
    at /home/hans/development/nym/nym-wallet/node_modules/webpack/lib/NormalModule.js:1048:4
    at processResult (/home/hans/development/nym/nym-wallet/node_modules/webpack/lib/NormalModule.js:763:11)
    at /home/hans/development/nym/nym-wallet/node_modules/webpack/lib/NormalModule.js:827:5 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v17.1.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```
However, the binary *nym-wallet* and *.deb* pkg are built but after running the binary this is what happens:
![image](https://user-images.githubusercontent.com/33793809/142918153-9a4c0067-5d8e-49fa-886d-3b1bcba97784.png)

**An example of perhaps another issue:**
At first I thought the unabillity to find `libsoup2.4` by `pkg-config` was causing the errors, because on Pop!OS 21.04 the pkg is actually called `libsoup2.4-1` but this problem was solved by installing `libsoup2.4-dev libwebkit2gtk-4.0-dev`

Not sure if this is really relevant but nevertheless I'm sharing the logs here:

```
error: failed to run custom build command for `soup-sys v0.10.0`

Caused by:
  process didn't exit successfully: `/home/hans/development/nym/nym-wallet/target/release/build/soup-sys-ce1581e744a25857/build-script-build` (exit status: 1)
  --- stdout
  cargo:rerun-if-env-changed=LIBSOUP_2.4_NO_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG
  cargo:rerun-if-env-changed=LIBSOUP_2.4_STATIC
  cargo:rerun-if-env-changed=LIBSOUP_2.4_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_STATIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_SYSROOT_DIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR

  --- stderr
  `"pkg-config" "--libs" "--cflags" "libsoup-2.4" "libsoup-2.4 >= 0.0"` did not exit successfully: exit status: 1
  --- stderr
  Package libsoup-2.4 was not found in the pkg-config search path.
  Perhaps you should add the directory containing `libsoup-2.4.pc'
  to the PKG_CONFIG_PATH environment variable
  No package 'libsoup-2.4' found
  Package libsoup-2.4 was not found in the pkg-config search path.
  Perhaps you should add the directory containing `libsoup-2.4.pc'
  to the PKG_CONFIG_PATH environment variable
  No package 'libsoup-2.4' found

warning: build failed, waiting for other jobs to finish...
error: build failed
Error: failed to build app

Caused by:
    Result of `cargo build` operation was unsuccessful: exit status: 101

 app:spawn Command "/home/hans/development/nym/nym-wallet/node_modules/@tauri-apps/cli/bin/tauri-cli" failed with exit code: 1 +0ms
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Which area of Nym were you using?**
 - Application: Wallet
 - OS: Pop!OS 21.04 
 - Version: develop branch

**Additional context**
This all could be my own fault, but probably there is an issue with using the latest Nodejs v 17.1.0 and [webpack](https://github.com/webpack/webpack/issues/14532) OR it can be some issue with Pop!OS 21.04 (Ubuntu 21.04) 

Please, try to see if you can actually build this without any issues with NodeJS 17.1.0

**Comment by gyrusdentatus** [comment]
Also the **nym-wallet_linux_0.1.0_amd64.AppImage** is crashing the same way after running it and trying to create a new address. 
Not sure if the error is on my side or not ... will try tomorrow. This is a really *mint* install of Pop!OS 21.04 so who knows :)... 
![image](https://user-images.githubusercontent.com/33793809/142924974-a28d79f6-a579-45ba-a3de-2521301751d2.png)

and in plain text: 
```(WebKitWebProcess:118362): Gdk-ERROR **: 20:40:58.653: The program 'WebKitWebProcess' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadValue (integer parameter out of range for operation)'.
  (Details: serial 216 error_code 2 request_code 151 (GLX) minor_code 34)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the GDK_SYNCHRONIZE environment
   variable to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)


```

**Comment by gyrusdentatus** [comment]
Ok, so the crashes as described in the second comment were solved by installing `libgtk-3-dev` it seems (also some additional stuff along with clang and cmake)
. 
Not sure if it wasn't the nvidia drivers which I installed last night but rebooted today and tried the app after installing `libgtk-3-dev`

Nvidia drivers:
`nvidia-xconfig:  version 470.86`
`

@mfahampshire @tommyv1987 please test it out guys on a mint Ubuntu 21.04 and maybe add it in the **prerequisites** in the **docs**

**Comment by tommyv1987** [comment]
Hi @gyrusdentatus thank you for raising this.

The current binaries and code have not been tested against this version of Ubuntu. I believe the version the code was developed against is `Ubuntu 20.04.2 LTS`. I will have a look and investigate the issue.

**Comment by gyrusdentatus** [comment]
On ParrotOS...debian-based distro (yeah I know it is a bit exotic but it doesn't matter in this case) I had problems with **node -v 17.0.1** but not on MacOS. 

Reverting to **node v16.8.0** worked and wallet was built. 
Not sure why this is happening on Linux and not on MacOS... 

Here is the err log:
```
user@parrot]─[~/nym/nym-wallet]
└──╼ $yarn build
yarn run v1.22.17
$ yarn run webpack:build & yarn run tauri:build
$ yarn tauri build
$ yarn webpack
$ /home/user/nym/nym-wallet/node_modules/.bin/tauri build
$ /home/user/nym/nym-wallet/node_modules/.bin/webpack
 app:spawn Running "/home/user/nym/nym-wallet/node_modules/@tauri-apps/cli/bin/tauri-cli tauri build" +0ms

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:130:10)
    at BulkUpdateDecorator.hashFactory (/home/user/nym/nym-wallet/node_modules/webpack/lib/util/createHash.js:145:18)
    at BulkUpdateDecorator.update (/home/user/nym/nym-wallet/node_modules/webpack/lib/util/createHash.js:46:50)
    at RawSource.updateHash (/home/user/nym/nym-wallet/node_modules/webpack-sources/lib/RawSource.js:70:8)
    at NormalModule._initBuildHash (/home/user/nym/nym-wallet/node_modules/webpack/lib/NormalModule.js:888:17)
    at handleParseResult (/home/user/nym/nym-wallet/node_modules/webpack/lib/NormalModule.js:954:10)
    at /home/user/nym/nym-wallet/node_modules/webpack/lib/NormalModule.js:1048:4
    at processResult (/home/user/nym/nym-wallet/node_modules/webpack/lib/NormalModule.js:763:11)
    at /home/user/nym/nym-wallet/node_modules/webpack/lib/NormalModule.js:827:5
    Updating git repository `https://github.com/nymtech/sphinx`
node:internal/crypto/hash:67
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:130:10)
    at BulkUpdateDecorator.hashFactory (/home/user/nym/nym-wallet/node_modules/webpack/lib/util/createHash.js:145:18)
    at BulkUpdateDecorator.update (/home/user/nym/nym-wallet/node_modules/webpack/lib/util/createHash.js:46:50)
    at RawSource.updateHash (/home/user/nym/nym-wallet/node_modules/webpack-sources/lib/RawSource.js:70:8)
    at NormalModule._initBuildHash (/home/user/nym/nym-wallet/node_modules/webpack/lib/NormalModule.js:888:17)
    at handleParseResult (/home/user/nym/nym-wallet/node_modules/webpack/lib/NormalModule.js:954:10)
    at /home/user/nym/nym-wallet/node_modules/webpack/lib/NormalModule.js:1048:4
    at processResult (/home/user/nym/nym-wallet/node_modules/webpack/lib/NormalModule.js:763:11)
    at /home/user/nym/nym-wallet/node_modules/webpack/lib/NormalModule.js:827:5 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v17.0.1
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by gyrusdentatus** [comment]
ok, the build failed on Linux with node 17.0.1 but it did not on MacOS. Weird. 

I wrote a simple guide here https://gist.github.com/gyrusdentatus/62a0ded66586c9e80072d7da125ce35c

**Comment by tommyv1987** [comment]
Hi @gyrusdentatus, 

I've recently put in a fix for production version of the webpack config. I appreciate the efforts you went to for providing the gist. I will use this to amend our README.md for the wallet.

Going to close this ticket, in lieu of amending the readme shortly.

**Comment by gyrusdentatus** [comment]
Thanks, @tommyv1987 ! I wrote the gist in one go while trying it out in VM on a somewhat exotic distro, ParrotOS but it's still  debian-based. 
Main reason for writing was to see if compiling it straight from source from the develop branch would help this person's issue #916 - It didn't :) 

I think the latest stable working version of `node` for the current wallet release is `17.0.1` , at least for Linux. 

But you for sure know better than me - so if this is just a webpack issue with an easy fix then I guess that's good news!
